import os

OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_API_KEY"
)

TWILIO_ACCOUNT_SID = os.getenv(
    "TWILIO_ACCOUNT_SID"
)

TWILIO_AUTH_TOKEN = os.getenv(
    "TWILIO_AUTH_TOKEN"
)

TWILIO_FROM_NUMBER = os.getenv(
    "TWILIO_FROM_NUMBER"
)

EMERGENCY_NUMBER = os.getenv(
    "EMERGENCY_NUMBER"
)